# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  NODE_VERSION: 14.x

on:
  push:
    branches:
      - master
      - feat/**
      - patch/**
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3.4.1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run test:lint
      env:
        CI: true

  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3.4.1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm test
      env:
        CI: true

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install modules
        run: npm ci
      - name: Generate coverage report
        run: npm run test:coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v1